version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: cache-service-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: cache_service
      MARIADB_USER: cache_user
      MARIADB_PASSWORD: cache_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - cache-network

volumes:
  mariadb_data:
    driver: local

networks:
  cache-network:
    driver: bridge